### PR TITLE
Dashboard UI Refresh

### PR DESCRIPTION
**Pull request by boxystudio**
I love this plugin! I spent some time this morning overhauling the UI. I updated the UI of the entire dashboard, switching out floats for flexboxes, adding embellishments throughout, etc.

### CODE REVIEW

**Comment by boxystudio** [comment]
New screenshot, if you'd like to update:

image

**Comment by jordymeow** [comment]
@boxystudio Sorry to ask you this, but couldn't find a way to do this easily. Any idea how I could get your pull request/changes into my own fork of edd-metrics? I also made some changes but would love to integrate yours.

**Comment by boxystudio** [comment]
> @boxystudio Sorry to ask you this, but couldn't find a way to do this easily. Any idea how I could get your pull request/changes into my own fork of edd-metrics? I also made some changes but would love to integrate yours.

Good question. I had to Google how to fork and submit a pull request, so I'm not sure I'll be of much help. I'm guessing you can fork my fork and submit that? 😃

[https://github.com/boxystudio/edd-metrics](url)

**Comment by scottopolis** [comment]
@boxystudio dude this looks amazing, thank you so much! I'll check this out and update the plugin, and add you to the contributors.

**Comment by scottopolis** [comment]
@boxystudio what's your .org username?

**Comment by boxystudio** [comment]
Awesome, thanks Scott!

**Pull request merged**
