### PR TITLE
Add edd commissions

### PR DESCRIPTION
**Pull request by growdev**
A fix for #30. 

I added a panel for 'Unpaid Commissions'.  On hover the number of unpaid commissions is shown.

screen shot 2016-10-02 at 1 08 42 pm

I left out the 30 day comparison because some people pay commissions  45 days out. We pay 15 days after end of month.

### CODE REVIEW

**Comment by scottopolis** [comment]
Thanks Daniel, actually the PHP warning from those arguments was because they weren't being used at all. They are only used for ajax, so I just deleted the args.

I just pushed some stuff, can you pull and resolve the conflicts for this PR?

**Comment by growdev** [comment]
Thanks, fixed those.

**Comment by scottopolis** [comment]
I don't have this add-on to test, but it looks ok to me. Thanks Daniel!

**Comment by scottopolis** [comment]
What's your .org username? I'll add you to the contributors.

**Comment by growdev** [comment]
It's growdev. Thanks!

**Pull request merged**
